### ISSUE TITLE
Compatibility with Android Wear 5.1.1

### ISSUE THREAD

**Issue by bignadad** [BoD/android-wear-color-picker#1]
Since the update to Android 5.1.1 this color picker is not working anymore. No crashes. When color is picked it does not make changes as it did before 5.1.1

**Comment by BoD** [comment]
I am using the library in my own app, and it works well on a Sony SmartWatch 3 running 5.1.1.

**Comment by bignadad** [comment]
K. Im running Logs now to see if i have something wrong. Im using the same app that was working before i updated and worked then.

**Comment by bignadad** [comment]
my onActivityResult is getting called with requestcode 0 and result code -1. so all that is good.

Then i have this to update watchface but doesn't update

switch (requestCode) {
            case 0:
                if (resultCode == org.jraf.android.androidwearcolorpicker.app.ColorPickActivity.RESULT_CANCELED) {
                    // The user pressed 'Cancel'
                    break;
                }
                int pickedColor = ColorPickActivity.getPickedColor(data);
                String hexColor = "#" + Integer.toHexString(pickedColor);
                PrefHelper.setConfigTickColor(getActivity(),hexColor);
                DataMap configKeysToOverwrite = new DataMap();
                configKeysToOverwrite.putInt(Constants.KEY_TICK_COLOR, pickedColor);
                AnalogWatchFaceUtil.overwriteKeysInConfigDataMap(mGoogleApiClient, configKeysToOverwrite);
                getActivity().finish();
                break;
        }

The color picker in my apps phone options work. Do you see anything wrong in that code?

This is the onClick intent code

 Intent intent = new ColorPickActivity.IntentBuilder().oldColor(Color.parseColor(PrefHelper.getConfigTickColor(getActivity()))).build(getActivity());
                startActivityForResult(intent, 0);

**Comment by BoD** [comment]
Your switch seems to be incorrect.  You have a case 0, then a break, then some code.  Aren't you missing a case?

**Comment by bignadad** [comment]
No the case that comes in is 0 so it goes into that case. if the result code is canceled (0) then it breaks otherwise it runs the rest of the code. the result code is -1 so it does not break

**Comment by BoD** [comment]
Ok sorry, indeed this is not incorrect.
But I am not sure I understand what you're saying.
Do you receive -1 (which is RESULT_OK) or 0 (RESULT_CANCELED) in resultCode?

**Comment by bignadad** [comment]
I debugged on my moto 360 5.1.1 and in logcat it shows the result code is -1 which is what it should be

**Comment by BoD** [comment]
So I am sorry but I don't understand what you are saying the problem is.  What exactly doesn't work?

**Comment by bignadad** [comment]
when i select color the result code is correct (-1) so it should be working. On watch the color selects (turns entire screen the color selected) but when it goes back to watchface the color does not change. Well... after typing all this out i am starting to think that its a problem with updating the watchface and not this library. I apologize for wasting your time. It has to be the following not working after 5.1.1 update. something changed in this update that causes my old method not to work

DataMap configKeysToOverwrite = new DataMap();
configKeysToOverwrite.putInt(Constants.KEY_TICK_COLOR, pickedColor);
AnalogWatchFaceUtil.overwriteKeysInConfigDataMap(mGoogleApiClient, configKeysToOverwrite);

**Comment by BoD** [comment]
No problem :-)
