### ISSUE TITLE
androidx update

### ISSUE THREAD

**Issue by lancelinksp** [BoD/android-wear-color-picker#4]
Will you be migrating to use androidx instead of the deprecated classes?
ColorPickActivity.kt:
android.support.v7.widget.LinearSnapHelper = androidx.recyclerview.widget.LinearSnapHelper
android.support.v7.widget.RecyclerView = androidx.recyclerview.widget.RecyclerView
android.support.wear.widget.CurvingLayoutCallback = androidx.wear.widget.CurvingLayoutCallback
android.support.wear.widget.WearableLinearLayoutManager = androidx.wear.widget.WearableLinearLayoutManager

ColorAdapter.kt:
android.support.v7.widget.RecyclerView = androidx.recyclerview.widget.RecyclerView

**Comment by BoD** [comment]
Yes I will.

Can't promise when, as I'm in vacation right now, but in the next few weeks.

**Comment by lancelinksp** [comment]
Thank you for the good news! Thanks for the work you have done on this project. Much appreciated, enjoy your vacation

**Comment by BoD** [comment]
Just published v2.2.2 which is based on AndroidX.
